apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: grafana
    environment: demo
    project: spam
spec:
  destination:
    namespace: grafana
    server: "https://kubernetes.default.svc"
  syncPolicy: {}
  project: spam
  revisionHistoryLimit: 3
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 10.1.4
      chart: grafana
      helm:
        releaseName: grafana
        valueFiles:
          - $values/argocd/applications/values/grafana.yaml
    - repoURL: "https://github.com/IPashkaYouNot/uni-spam.git"
      targetRevision: "argo-setup"
      ref: values
